export const MOCK_CATEGORIES = [
    { id: 'cat-1', name: 'Premium Attar', slug: 'attar', icon: 'Sparkles', count: 24 },
    { id: 'cat-2', name: 'Home Decor', slug: 'home-decor', icon: 'Home', count: 18 },
    { id: 'cat-3', name: 'Organic Skincare', slug: 'skincare', icon: 'Heart', count: 12 },
    { id: 'cat-4', name: 'Handcrafted Gifts', slug: 'gifts', icon: 'Gift', count: 15 },
    { id: 'cat-5', name: 'Lifestyle Accessories', slug: 'accessories', icon: 'Watch', count: 30 },
];

export const MOCK_PRODUCTS = [
    {
        id: 'prod-1',
        name: 'Dehn Al Oudh Royale - Premium Attar 6ml',
        slug: 'dehn-al-oudh-royale',
        description: 'A rich, deep, authentic wooden fragrance aged for optimal richness. 100% alcohol-free premium concentrated perfume oil.',
        price: 1850,
        previousPrice: 2200,
        discount: 16,
        image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
        category: 'attar',
        rating: 4.9,
        reviewCount: 42,
        stock: 15,
        isFeatured: true,
        isBestSeller: true,
        isNewArrival: false,
    },
    {
        id: 'prod-2',
        name: 'Handcrafted Brass Islamic Table Decor',
        slug: 'brass-table-decor',
        description: 'Elegantly crafted solid brass decor with fine Arabic calligraphy details for your living area or workplace.',
        price: 3400,
        previousPrice: 4000,
        discount: 15,
        image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800',
        category: 'home-decor',
        rating: 4.8,
        reviewCount: 18,
        stock: 8,
        isFeatured: true,
        isBestSeller: false,
        isNewArrival: true,
    },
    {
        id: 'prod-3',
        name: 'Organic Black Seed Oil - Cold Pressed 250ml',
        slug: 'organic-black-seed-oil',
        description: '100% pure cold-pressed Nigella Sativa oil rich in antioxidants and vital nutrients.',
        price: 650,
        previousPrice: 750,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&q=80&w=800',
        category: 'skincare',
        rating: 4.7,
        reviewCount: 89,
        stock: 40,
        isFeatured: false,
        isBestSeller: true,
        isNewArrival: false,
    },
    {
        id: 'prod-4',
        name: 'Luxury Velvet Prayer Mat (Janamaz)',
        slug: 'luxury-velvet-prayer-mat',
        description: 'Ultra-soft plush velvet prayer mat with ergonomic foam padding for supreme comfort during prayer.',
        price: 1250,
        previousPrice: 1500,
        discount: 16,
        image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=800',
        category: 'lifestyle',
        rating: 5.0,
        reviewCount: 65,
        stock: 22,
        isFeatured: true,
        isBestSeller: true,
        isNewArrival: true,
    }
];